/**
 * gen-go-types.ts — generate TypeScript types from the Go backend.
 *
 * The Go structs are the single source of truth. Run this after changing a Go
 * model and the frontend will fail to compile wherever it drifted.
 *
 *   yarn gen:types          # write src/types/generated/*.ts
 *   yarn gen:types:check    # exit 1 if output is stale (CI guard)
 *
 * What it converts (see CONFIG below):
 *   - structs in `dto/` and `domain/`  -> `export interface`
 *   - const blocks in `constants/`     -> `as const` object + union type
 *
 * Field rules (mirrors Go's encoding/json):
 *   - `json:"name"`            -> property `name`
 *   - `json:"name,omitempty"`  -> optional property
 *   - `json:"-"`               -> dropped (e.g. User.Password / User.Salt)
 *   - no tag                   -> Go field name verbatim
 *   - unexported (lowercase)   -> dropped (Go never marshals it)
 *   - `*T`                     -> optional `name?: T | null`
 *
 * Deliberately NOT converted: db/ (sqlc rows, no json tags), service/handler/
 * repository wiring structs. Add packages to CONFIG.structDirs if that changes.
 *
 * This is a dev tool — it is excluded from the app's tsconfig and run via tsx.
 * It uses a line-based parser, not a full Go parser: it handles the constructs
 * present in this codebase and emits `unknown` + a TODO for anything it can't map.
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from 'node:fs';
import { basename, join, relative, resolve } from 'node:path';

// ----------------------------------------------------------------------------
// Configuration
// ----------------------------------------------------------------------------

interface ConstSource {
  file: string; // path relative to the api root
  objectName: string; // emitted `export const <objectName>`
  unionName: string; // emitted `export type <unionName>`
}

const CWD = process.cwd();

const CONFIG = {
  // Override with LOV_API_DIR if the api lives elsewhere.
  apiRoot: resolve(process.env.LOV_API_DIR ?? join(CWD, '..', 'api')),
  outDir: join(CWD, 'src', 'types', 'generated'),
  // Each dir -> one generated module (e.g. dto/ -> dto.ts).
  structDirs: ['dto', 'domain'],
  constSources: [
    { file: 'constants/roles.go', objectName: 'Roles', unionName: 'RoleId' },
    { file: 'constants/permissions.go', objectName: 'Permissions', unionName: 'Permission' },
  ] satisfies ConstSource[],
};

const CHECK_MODE = process.argv.includes('--check');

// Go type -> TS type. Things that need null (pgtype/sql.Null*) carry it here.
const SCALAR_MAP: Record<string, string> = {
  string: 'string',
  bool: 'boolean',
  int: 'number',
  int8: 'number',
  int16: 'number',
  int32: 'number',
  int64: 'number',
  uint: 'number',
  uint8: 'number',
  uint16: 'number',
  uint32: 'number',
  uint64: 'number',
  float32: 'number',
  float64: 'number',
  byte: 'number',
  rune: 'number',
  'time.Time': 'string',
  'time.Duration': 'number',
  'uuid.UUID': 'string',
  'json.RawMessage': 'unknown',
  'pgtype.Text': 'string | null',
  'pgtype.Timestamp': 'string | null',
  'pgtype.Timestamptz': 'string | null',
  'pgtype.Date': 'string | null',
  'pgtype.UUID': 'string | null',
  'pgtype.Int4': 'number | null',
  'pgtype.Int8': 'number | null',
  'pgtype.Bool': 'boolean | null',
  'pgtype.Numeric': 'number | null',
  'sql.NullString': 'string | null',
  'sql.NullInt32': 'number | null',
  'sql.NullInt64': 'number | null',
  'sql.NullBool': 'boolean | null',
  'sql.NullTime': 'string | null',
  'sql.NullFloat64': 'number | null',
};

// ----------------------------------------------------------------------------
// Generator
// ----------------------------------------------------------------------------

const warnings: string[] = [];
// Bare struct name -> module it lives in (for cross-module imports).
const registry = new Map<string, string>();

const rel = (p: string): string => relative(CWD, p) || p;

const header = (source: string): string =>
  `// Code generated by scripts/gen-go-types.ts from the Go backend. DO NOT EDIT.\n` +
  `// Source: ${source}\n` +
  `// Regenerate: yarn gen:types\n`;

function listGoFiles(dir: string): string[] {
  const abs = join(CONFIG.apiRoot, dir);
  if (!existsSync(abs)) {
    warnings.push(`struct dir not found: ${rel(abs)}`);
    return [];
  }
  return readdirSync(abs)
    .filter((f) => f.endsWith('.go') && !f.endsWith('_test.go'))
    .sort()
    .map((f) => join(abs, f));
}

interface ParsedStruct {
  name: string;
  bodyLines: string[];
}

/** Extract every `type X struct { ... }` from a Go source file. */
function extractStructs(src: string): ParsedStruct[] {
  const lines = src.split('\n');
  const out: ParsedStruct[] = [];

  for (let i = 0; i < lines.length; i++) {
    const open = /^type\s+([A-Za-z_]\w*)\s+struct\s*\{(.*)$/.exec(
      (lines[i] ?? '').trim(),
    );
    if (!open) continue;

    const name = open[1] ?? '';
    const rest = open[2] ?? '';
    const body: string[] = [];

    if (rest.includes('}')) {
      // single-line struct, e.g. `type X struct {}`
      const inner = rest.slice(0, rest.indexOf('}')).trim();
      if (inner) body.push(inner);
    } else {
      let depth = 1;
      for (let j = i + 1; j < lines.length; j++) {
        const line = lines[j] ?? '';
        depth += (line.match(/\{/g) ?? []).length;
        depth -= (line.match(/\}/g) ?? []).length;
        if (depth <= 0) {
          i = j;
          break;
        }
        body.push(line);
      }
    }
    out.push({ name, bodyLines: body });
  }
  return out;
}

function recordImport(
  typeName: string,
  currentModule: string,
  imports: Set<string>,
): void {
  const mod = registry.get(typeName);
  if (mod && mod !== currentModule) {
    imports.add(`import type { ${typeName} } from './${mod}';`);
  }
}

/** Map a Go type expression to a TS type. Records cross-module imports. */
function mapGoType(
  raw: string,
  currentModule: string,
  imports: Set<string>,
): { ts: string; nullable: boolean } {
  let g = raw.trim();
  let nullable = false;

  if (g.startsWith('*')) {
    nullable = true;
    g = g.slice(1).trim();
  }

  if (g.startsWith('[]')) {
    const elem = g.slice(2).trim();
    if (elem === 'byte') return { ts: 'string', nullable }; // []byte -> base64
    const inner = mapGoType(elem, currentModule, imports);
    const innerTs = inner.nullable ? `${inner.ts} | null` : inner.ts;
    return { ts: `Array<${innerTs}>`, nullable };
  }

  if (g.startsWith('map[')) {
    const close = g.indexOf(']');
    const key = g.slice(4, close).trim();
    const val = g.slice(close + 1).trim();
    const keyTs = /^u?int/.test(key) ? 'number' : 'string';
    const v = mapGoType(val, currentModule, imports);
    const valTs = v.nullable ? `${v.ts} | null` : v.ts;
    return { ts: `Record<${keyTs}, ${valTs}>`, nullable };
  }

  const scalar = SCALAR_MAP[g];
  if (scalar) return { ts: scalar, nullable };

  if (g === 'interface{}' || g === 'any') return { ts: 'unknown', nullable };

  const bare = g.includes('.') ? (g.split('.').pop() ?? g) : g;
  if (registry.has(bare)) {
    recordImport(bare, currentModule, imports);
    return { ts: bare, nullable };
  }

  warnings.push(`unmapped Go type '${raw}' -> unknown`);
  return { ts: `unknown /* ${raw} */`, nullable };
}

type Field =
  | { kind: 'prop'; name: string; tsType: string; optional: boolean }
  | { kind: 'extends'; typeName: string }
  | { kind: 'skip' }
  | { kind: 'todo'; raw: string };

/** Parse one struct body line (may yield multiple props for `A, B Type`). */
function parseFieldLine(
  rawLine: string,
  currentModule: string,
  imports: Set<string>,
): Field[] {
  let line = rawLine;

  // Pull out the struct tag (backticks) before touching comments.
  let tag = '';
  const tagMatch = /`([^`]*)`/.exec(line);
  if (tagMatch) {
    tag = tagMatch[1] ?? '';
    line = line.slice(0, tagMatch.index) + line.slice(tagMatch.index + tagMatch[0].length);
  }
  const commentAt = line.indexOf('//');
  if (commentAt >= 0) line = line.slice(0, commentAt);
  line = line.trim();
  if (!line) return [{ kind: 'skip' }];

  // json tag: name + omitempty, or `-` to drop.
  let jsonName: string | null = null;
  let omitempty = false;
  const jsonMatch = /json:"([^"]*)"/.exec(tag);
  if (jsonMatch) {
    const parts = (jsonMatch[1] ?? '').split(',');
    jsonName = parts[0] ?? '';
    omitempty = parts.slice(1).includes('omitempty');
    if (jsonName === '-') return [{ kind: 'skip' }];
  }

  const tokens = line.split(/\s+/).filter(Boolean);

  // Embedded field: a lone type with no field name -> TS `extends`.
  if (tokens.length === 1) {
    const emb = (tokens[0] ?? '').replace(/^\*/, '');
    const bare = emb.includes('.') ? (emb.split('.').pop() ?? emb) : emb;
    if (registry.has(bare)) {
      recordImport(bare, currentModule, imports);
      return [{ kind: 'extends', typeName: bare }];
    }
    return [{ kind: 'todo', raw: line }];
  }

  const goType = tokens[tokens.length - 1] ?? '';
  const namePart = tokens.slice(0, -1).join(' ');
  const fieldNames = namePart.split(',').map((s) => s.trim()).filter(Boolean);

  const mapped = mapGoType(goType, currentModule, imports);

  return fieldNames.map((goName): Field => {
    // Unexported fields are never serialized by Go.
    if (/^[a-z]/.test(goName) && !jsonName) return { kind: 'skip' };
    const name = jsonName && jsonName.length ? jsonName : goName;
    const optional = omitempty || mapped.nullable;
    const tsType =
      mapped.nullable && !mapped.ts.includes('null')
        ? `${mapped.ts} | null`
        : mapped.ts;
    return { kind: 'prop', name, tsType, optional };
  });
}

function renderStruct(
  struct: ParsedStruct,
  currentModule: string,
  imports: Set<string>,
): string {
  const props: string[] = [];
  const extendsList: string[] = [];

  for (const raw of struct.bodyLines) {
    for (const field of parseFieldLine(raw, currentModule, imports)) {
      if (field.kind === 'skip') continue;
      if (field.kind === 'extends') extendsList.push(field.typeName);
      else if (field.kind === 'todo') props.push(`  // TODO: unparsed -> ${field.raw}`);
      else props.push(`  ${field.name}${field.optional ? '?' : ''}: ${field.tsType};`);
    }
  }

  const ext = extendsList.length ? ` extends ${extendsList.join(', ')}` : '';
  const body = props.length ? `\n${props.join('\n')}\n` : '';
  return `export interface ${struct.name}${ext} {${body}}\n`;
}

function buildStructModule(dir: string): { module: string; content: string } | null {
  const files = listGoFiles(dir);
  if (!files.length) return null;

  const module = basename(dir);
  const imports = new Set<string>();
  const blocks: string[] = [];

  for (const file of files) {
    for (const struct of extractStructs(readFileSync(file, 'utf8'))) {
      blocks.push(renderStruct(struct, module, imports));
    }
  }
  if (!blocks.length) return null;

  const importBlock = imports.size ? `\n${[...imports].sort().join('\n')}\n` : '';
  return {
    module,
    content: `${header(`api/${dir}/*.go`)}${importBlock}\n${blocks.join('\n')}`,
  };
}

function parseConstEntries(src: string): Array<[string, string]> {
  const entries: Array<[string, string]> = [];
  const blockRe = /const\s*\(([\s\S]*?)\)/g;
  let block: RegExpExecArray | null;

  while ((block = blockRe.exec(src))) {
    for (const rawLine of (block[1] ?? '').split('\n')) {
      const commentAt = rawLine.indexOf('//');
      const line = (commentAt >= 0 ? rawLine.slice(0, commentAt) : rawLine).trim();
      if (!line) continue;

      const match = /^([A-Za-z_]\w*)\s*=\s*(.+)$/.exec(line);
      if (!match) continue;
      const key = match[1] ?? '';
      const value = (match[2] ?? '').trim();

      if (/^"(?:[^"\\]|\\.)*"$/.test(value) || /^-?\d+(?:\.\d+)?$/.test(value)) {
        entries.push([key, value]);
      } else {
        warnings.push(`skipped const ${key} = ${value} (unsupported value)`);
      }
    }
  }
  return entries;
}

function buildConstModule(): string | null {
  const blocks: string[] = [];
  const sources: string[] = [];

  for (const source of CONFIG.constSources) {
    const abs = join(CONFIG.apiRoot, source.file);
    if (!existsSync(abs)) {
      warnings.push(`const source not found: ${rel(abs)}`);
      continue;
    }
    const entries = parseConstEntries(readFileSync(abs, 'utf8'));
    if (!entries.length) {
      warnings.push(`no constants parsed from ${source.file}`);
      continue;
    }
    sources.push(`api/${source.file}`);
    const objBody = entries.map(([k, v]) => `  ${k}: ${v},`).join('\n');
    blocks.push(
      `export const ${source.objectName} = {\n${objBody}\n} as const;\n\n` +
        `export type ${source.unionName} =\n` +
        `  (typeof ${source.objectName})[keyof typeof ${source.objectName}];\n`,
    );
  }

  if (!blocks.length) return null;
  return `${header(sources.join(', '))}\n${blocks.join('\n')}`;
}

function buildIndex(modules: string[]): string {
  const exports = modules.map((m) => `export * from './${m}';`).join('\n');
  return `${header('generated modules')}\n${exports}\n`;
}

// ----------------------------------------------------------------------------
// Run
// ----------------------------------------------------------------------------

// Pass 1: register every struct name so cross-module references resolve.
for (const dir of CONFIG.structDirs) {
  const module = basename(dir);
  for (const file of listGoFiles(dir)) {
    for (const struct of extractStructs(readFileSync(file, 'utf8'))) {
      const existing = registry.get(struct.name);
      if (existing && existing !== module) {
        warnings.push(
          `duplicate type '${struct.name}' in ${existing} and ${module}; references may be ambiguous`,
        );
      }
      registry.set(struct.name, module);
    }
  }
}

// Pass 2: build every output file.
const targets: Array<{ file: string; content: string }> = [];
const moduleNames: string[] = [];

for (const dir of CONFIG.structDirs) {
  const built = buildStructModule(dir);
  if (built) {
    targets.push({ file: join(CONFIG.outDir, `${built.module}.ts`), content: built.content });
    moduleNames.push(built.module);
  }
}

const constContent = buildConstModule();
if (constContent) {
  targets.push({ file: join(CONFIG.outDir, 'constants.ts'), content: constContent });
  moduleNames.push('constants');
}

targets.push({ file: join(CONFIG.outDir, 'index.ts'), content: buildIndex(moduleNames) });

for (const warning of warnings) console.warn(`⚠ ${warning}`);

if (CHECK_MODE) {
  const stale = targets.filter(
    (t) => !existsSync(t.file) || readFileSync(t.file, 'utf8') !== t.content,
  );
  if (stale.length) {
    console.error('\n✖ Generated types are out of date. Run `yarn gen:types`. Affected:');
    for (const t of stale) console.error(`  - ${rel(t.file)}`);
    process.exit(1);
  }
  console.log('✓ Generated types are up to date.');
} else {
  mkdirSync(CONFIG.outDir, { recursive: true });
  for (const t of targets) writeFileSync(t.file, t.content);
  console.log(`✓ Generated ${targets.length} file(s) in ${rel(CONFIG.outDir)} from ${rel(CONFIG.apiRoot)}:`);
  for (const t of targets) console.log(`  - ${rel(t.file)}`);
}
